/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Const, ConstInterface } from "../Const";

const _abi = [
  {
    inputs: [],
    name: "BASE_DECIMALS",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BONE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BPOW_PRECISION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_BPOW_BASE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_BPOW_BASE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061018d806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c8063189d00ca1461005c5780638b09578d14610077578063ba019dab14610091578063bc694ea214610099578063c36596a6146100a1575b600080fd5b6100646100b0565b6040519081526020015b60405180910390f35b61007f601281565b60405160ff909116815260200161006e565b610064600181565b6100646100ca565b610064670de0b6b3a764000081565b6100c76402540be400670de0b6b3a76400006100e9565b81565b60016100df670de0b6b3a7640000600261010b565b6100c7919061012a565b60008261010657634e487b7160e01b600052601260045260246000fd5b500490565b600081600019048311821515161561012557610125610141565b500290565b60008282101561013c5761013c610141565b500390565b634e487b7160e01b600052601160045260246000fdfea26469706673582212205ccc2b304a4b053e33bbbff6e378c8aa5991d410804786ccbc1bcfd902c0014664736f6c63430008060033";

export class Const__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Const> {
    return super.deploy(overrides || {}) as Promise<Const>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Const {
    return super.attach(address) as Const;
  }
  connect(signer: Signer): Const__factory {
    return super.connect(signer) as Const__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ConstInterface {
    return new utils.Interface(_abi) as ConstInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Const {
    return new Contract(address, _abi, signerOrProvider) as Const;
  }
}
